stages:
  - build
  - test
  - collect_artifacts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .docker_ccache

build_wheel_debug_linux_python27:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - apk add bash
    - bash scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4 --debug --docker-python2.7 --skip_doc
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_wheel_linux_python27:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - apk add bash
    - bash scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4 --docker-python2.7
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_wheel_linux_python35:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - apk add bash
    - bash scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4 --docker-python3.5 --skip_doc
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_wheel_linux_python36:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - apk add bash
    - bash scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4 --docker-python3.6 --skip_doc
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_wheel_mac_10_14_python27:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: build
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv"
    - source scripts/use_ccache.sh
    - bash scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_wheel_mac_10_14_python35:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: build
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.5/bin/virtualenv"
    - source scripts/use_ccache.sh
    - bash scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_wheel_mac_10_14_python36:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: build
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - source scripts/use_ccache.sh
    - bash scripts/make_wheel.sh --skip_test --skip_cpp_test --build_number=$CI_PIPELINE_ID --num_procs=4
  artifacts:
    expire_in: 1 day
    paths:
      - target/

build_dylib_macos_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: build
  script:
    - source scripts/use_ccache.sh
    - ./configure --no-visualization --no-python --release-opt-for-size
    - cd release/src/deployment
    - make -j8
  artifacts:
    expire_in: 1 day
    paths:
      - release/src/deployment/libAudioPreprocessing.dylib
      - release/src/deployment/libRecommender.dylib

build_dylib_ios_12:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: build
  script:
    - source scripts/use_ccache.sh
    - ./configure --no-visualization --no-python --release-opt-for-size --target-ios
    - cd release/src/deployment
    - make -j8
  artifacts:
    expire_in: 1 day
    paths:
      - release/src/deployment/libAudioPreprocessing.dylib
      - release/src/deployment/libRecommender.dylib

test_cpp_linux:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - build_wheel_linux_python27
  script:
    - apk add bash
    - apk add python2
    - python scripts/run_cpp_tests.py -j 2 --docker

test_cpp_mac_10_13:
  tags:
    - macos10.13
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python27
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv"
    - (test -d debug && test -d release) || ./configure
    - cd release/test
    - make -j8
    - export LD_LIBRARY_PATH=`pwd`/deps/local/lib:`pwd`/deps/local/lib64:$LD_LIBRARY_PATH
    - export PATH=`pwd`/deps/local/bin:$PATH
    - export LD_LIBRARY_PATH=`pwd`/src/unity:`pwd`/src/python/turicreate:$LD_LIBRARY_PATH
    - python ../../scripts/run_cpp_tests.py -j 2

test_cpp_mac_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python27
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv"
    - (test -d debug && test -d release) || ./configure
    - cd release/test
    - make -j8
    - export LD_LIBRARY_PATH=`pwd`/deps/local/lib:`pwd`/deps/local/lib64:$LD_LIBRARY_PATH
    - export PATH=`pwd`/deps/local/bin:$PATH
    - export LD_LIBRARY_PATH=`pwd`/src/unity:`pwd`/src/python/turicreate:$LD_LIBRARY_PATH
    - python ../../scripts/run_cpp_tests.py -j 2

test_python_linux_python27:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - build_wheel_linux_python27
  script:
    - apk add bash
    - bash scripts/test_wheel.sh --docker-python2.7
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_linux_python35:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - build_wheel_linux_python35
  script:
    - apk add bash
    - bash scripts/test_wheel.sh --docker-python3.5
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_linux_python36:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - build_wheel_linux_python36
  script:
    - apk add bash
    # TODO get python 3.6 working on a test image
    - bash scripts/test_wheel.sh --docker-python3.6
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_mac_python27_10_13:
  tags:
    - macos10.13
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python27
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv"
    - bash scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_mac_python27_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python27
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv"
    - bash scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_mac_python35_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python35
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.5/bin/virtualenv"
    - bash scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

test_python_mac_python36_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python36
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/3.6/bin/virtualenv"
    - bash scripts/test_wheel.sh
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - pytest.*

scenario_tests_linux_python27:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - build_wheel_linux_python27
  script:
    - apk add bash
    - cd scenario-tests
    - ./run_scenario_tests.sh --docker-python2.7 ../target/turicreate-*.whl

scenario_tests_linux_python35:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - build_wheel_linux_python35
  script:
    - apk add bash
    - cd scenario-tests
    - ./run_scenario_tests.sh --docker-python3.5 ../target/turicreate-*.whl

scenario_tests_linux_python36:
  tags:
    - docker
  services:
    - docker:dind
  image: docker:stable
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  dependencies:
    - build_wheel_linux_python36
  script:
    - apk add bash
    - cd scenario-tests
    - ./run_scenario_tests.sh --docker-python3.6 ../target/turicreate-*.whl

scenario_tests_mac_python27_10_13:
  tags:
    - macos10.13
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python27
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv"
    - cd scenario-tests
    - ./run_scenario_tests.sh ../target/turicreate-*.whl

scenario_tests_mac_python27_10_14:
  tags:
    - macos10.14
  only:
    variables:
      - $TC_HAS_MACOS_RUNNERS == "1"
  stage: test
  dependencies:
    - build_wheel_mac_10_14_python27
  script:
    - export VIRTUALENV="/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv"
    - cd scenario-tests
    - ./run_scenario_tests.sh ../target/turicreate-*.whl

collect_artifacts:
  tags:
    - docker
  services:
    - docker:dind
  image: alpine:latest
  stage: collect_artifacts
  dependencies:
    - build_dylib_ios_12
    - build_dylib_macos_10_14
    - build_wheel_linux_python27
    - build_wheel_linux_python35
    - build_wheel_linux_python36
    - build_wheel_mac_10_14_python27
    - build_wheel_mac_10_14_python35
    - build_wheel_mac_10_14_python36
  script:
    - mv release/src/deployment/*.dylib target/
    - rmdir -p release || find release
  artifacts:
    expire_in: 2 weeks
    paths:
      - target/

