language: cpp
sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    - SASS_LIBSASS_PATH=$TRAVIS_BUILD_DIR/libsass
  matrix:
    - AUTOTOOLS=no BUILD=shared
    - AUTOTOOLS=no BUILD=static
    - AUTOTOOLS=yes BUILD=shared
    - AUTOTOOLS=yes BUILD=static

before_install:
  - gem install sass
  - git clone https://github.com/sass/libsass.git

script:
  - ./script/ci-build-libsass

after_success:
  - ./build/bin/sassc -v
  - ldd ./build/bin/sassc
