# vim: set ft=dockerfile:

# This image is intended for building Turi Create for maximum compatibility
# with various Linux distributions.
# Based on Ubuntu 10.04 for compatibility with older glibc versions.
# Builds llvm 3.5.2 from source using GCC 4.8, then builds llvm 8.0.0 with clang and libc++,
# using libstdc++ ABI 4.8 for ABI compatibility with older libstdc++ versions.

FROM ubuntu:10.04

# Prevent apt-get from asking questions and expecting answers
ENV DEBIAN_FRONTEND noninteractive

# Set env variables for tools to pick up
ENV CC="gcc-4.8"
ENV CXX="g++-4.8"
ENV PATH="/usr/local/bin:${PATH}"
ENV CCACHE_DIR=/build/.docker_ccache
ENV CCACHE_COMPILERCHECK=content

# Fix path to new location for older Ubuntu releases
RUN sed -i -e 's/archive\./old-releases\./g' /etc/apt/sources.list

# Update package database
RUN apt-get update

# Install add-apt-repository and set up PPA for GCC 4.8 and git
RUN apt-get -y install python-software-properties
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN add-apt-repository ppa:git-core/ppa
RUN apt-get update

# Install dependencies
RUN apt-get -y install vim-common gcc-4.8 g++-4.8 libgif-dev libx11-dev ccache make zlib1g-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev perl-modules patch rsync git xz-utils file

# Install cmake from binary release
ADD https://cmake.org/files/v3.13/cmake-3.13.4-Linux-x86_64.tar.gz /opt/cmake-3.13.4-Linux-x86_64.tar.gz
WORKDIR /opt
RUN tar xf cmake-3.13.4-Linux-x86_64.tar.gz
ENV PATH="/opt/cmake-3.13.4-Linux-x86_64/bin:${PATH}"

# Install OpenSSL from source
# The built-in SSL is so old it can't talk to anything on the internet anymore
# (so even get-pip.py doesn't work!)
ADD https://www.openssl.org/source/openssl-1.1.0j.tar.gz /src/openssl-1.1.0j.tar.gz
WORKDIR /src
RUN tar xf openssl-1.1.0j.tar.gz
WORKDIR /src/openssl-1.1.0j
RUN ./config --prefix=/usr/local
RUN make -j4 --quiet
RUN make install
RUN ldconfig

# Install Python 2.7 from source
ADD http://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz /src/Python-2.7.15.tgz
WORKDIR /src
RUN tar xf Python-2.7.15.tgz
WORKDIR /src/Python-2.7.15
RUN ./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared --enable-loadable-sqlite-extensions
RUN make -j4 --quiet
RUN make install
RUN ldconfig

# Install Python 3.5 from source
ADD https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tgz /src/Python-3.5.6.tgz
WORKDIR /src
RUN tar xf Python-3.5.6.tgz
WORKDIR /src/Python-3.5.6
RUN ./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared --enable-loadable-sqlite-extensions
RUN make -j4 --quiet
RUN make install
RUN ldconfig

# Install Python 3.6 from source
ADD https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz /src/Python-3.6.8.tgz
WORKDIR /src
RUN tar xf Python-3.6.8.tgz
WORKDIR /src/Python-3.6.8
RUN ./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared --enable-loadable-sqlite-extensions
RUN make -j4 --quiet
RUN make install
RUN ldconfig

# Install pip and virtualenv
ADD https://bootstrap.pypa.io/get-pip.py /src/get-pip.py
WORKDIR /src
RUN python2.7 get-pip.py
RUN pip2.7 install virtualenv
RUN python3.5 get-pip.py
RUN pip3.5 install virtualenv
RUN python3.6 get-pip.py
RUN pip3.6 install virtualenv

# Install llvm 3.5.2 from source with clang
ADD https://releases.llvm.org/3.5.2/llvm-3.5.2.src.tar.xz /src/llvm-3.5.2.src.tar.xz
ADD https://releases.llvm.org/3.5.2/cfe-3.5.2.src.tar.xz /src/cfe-3.5.2.src.tar.xz
WORKDIR /src
RUN tar xf llvm-3.5.2.src.tar.xz
RUN tar xf cfe-3.5.2.src.tar.xz
RUN mv cfe-3.5.2.src llvm-3.5.2.src/tools/clang
RUN mkdir llvm-3.5.2.build
WORKDIR /src/llvm-3.5.2.build
RUN cmake ../llvm-3.5.2.src/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8  -DLIBCXX_CXX_ABI=libstdc++
RUN make -j24
RUN make install

# Install llvm 8.0 from source with clang and libc++ (no libc++abi)
ADD https://releases.llvm.org/8.0.0/llvm-8.0.0.src.tar.xz /src/llvm-8.0.0.src.tar.xz
ADD https://releases.llvm.org/8.0.0/cfe-8.0.0.src.tar.xz /src/cfe-8.0.0.src.tar.xz
ADD https://releases.llvm.org/8.0.0/libcxx-8.0.0.src.tar.xz /src/libcxx-8.0.0.src.tar.xz
WORKDIR /src
RUN tar xf llvm-8.0.0.src.tar.xz
RUN tar xf cfe-8.0.0.src.tar.xz
RUN tar xf libcxx-8.0.0.src.tar.xz
RUN mv cfe-8.0.0.src llvm-8.0.0.src/tools/clang
RUN mv libcxx-8.0.0.src llvm-8.0.0.src/projects/libcxx
RUN mkdir llvm-8.0.0.build
WORKDIR /src/llvm-8.0.0.build
RUN cmake ../llvm-8.0.0.src/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLIBCXX_CXX_ABI=libstdc++ -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON
RUN make -j24
RUN make install

# Copy cxxabi.h into a path it will be found in
RUN find /usr/include -name 'cxxabi.h'
RUN cp /usr/include/c++/4.8/cxxabi.h /usr/local/include/
RUN mkdir -p /usr/local/include/bits
RUN cp /usr/include/c++/4.8/x86_64-linux-gnu/bits/cxxabi_tweaks.h /usr/local/include/bits/
RUN cp /usr/include/c++/4.8/x86_64-linux-gnu/bits/c++config.h /usr/local/include/bits/

# Start at repo root (mounted into Docker)
WORKDIR /build

# Set ccache size to 4GB
CMD mkdir -p $CCACHE_DIR
CMD ccache -s
CMD ccache -M 4G

# Make clang the default compiler
ENV CC="clang"
ENV CXX="clang++"
